- name: dataypes
  hosts: local
  connection: local
  vars:
    length: 123
    title: "ci/cd pipeline mastery"
    is_true: true
    tools:
    - linux
    - shell
    - ansible
    concepts:
      ci: jenkins
      scripting: "shell, ansible, terraform, python"
  tasks:
  - name: printing vars
    ansible.builtin.debug:
      msg: "lenght is : {{ length }}, title is : {{ title }}, tools are : {{ tools }}, concepts are : {{ concepts }}"