- name: play level variables
  hosts: local
  connection: local
  vars_files:
  - infovars.yaml
  tasks:
  - name: print the server provisioning details
    ansible.builtin.debug:
      msg: "Server {{ SERVER_NAME }} is being provisioned for the {{ ENVIRONMENT }} environment by the {{ OWNER }}."